### ISSUE TITLE
variable length list codec

### ISSUE THREAD

**Issue by rolandjohann** [scodec/scodec#112]
We have blobs generated from existing systems, whose protocol contains of nested blocks. The last block can contain less elements than usual. The file ends there.

https://github.com/scodec/scodec/blob/3f922e7c758db3cc17169a73cf69cb2b9de1ab74/shared/src/main/scala/scodec/codecs/package.scala#L1336
`scodec.codecs.ListCodec#ListCodec` is capable to handle this case by specifying a `limit`, but `scodec.codecs#list` doesnt' provide this argument.

Is there a reason why this particular API is not published? We would appreciate a method like `listOfAtLeastN` or something like this.

**Comment by aartigao** [comment]
I know I'm necro-bumping a +4 years question but... I don't understood it 🤔 

Isn't `listOfN` what you were looking for? 👀
