### ISSUE TITLE
1.10.4 release?

### ISSUE THREAD

**Issue by alissapajer** [scodec/scodec#118]
I saw in the [changelog](https://github.com/scodec/scodec/blob/dfdb101b1c39cb6c47a829acff54d631a379e83d/CHANGELOG.md) that `1.10.4` is now publishing the  `testkit`! Yay! But it doesn't appear that `1.10.4` has been released (there is no tag and it's not in maven central). I was wondering if this was meant to be released? Thanks :)

**Comment by mpilquist** [comment]
Looks like the CHANGELOG was updated when that change was made but we still haven't released 1.10.4. I could do so today or tomorrow if you are interested though.

**Comment by TimothyKlim** [comment]
@mpilquist any updates?

**Comment by mpilquist** [comment]
Sorry for the delay -- I was hoping to get 2.13 milestone build support in to 1.10.4 but that's been problematic w.r.t. binary compatibility. I'll release 1.10.4 now.

**Comment by mpilquist** [comment]
1.10.4 has been released
