### ISSUE TITLE
Question: Leverage ordering in `discriminated` codec to facilitate migration

### ISSUE THREAD

**Issue by pm47** [scodec/scodec#122]
Hello, I'm using scodec to serialize data to a persistent db. Would you consider it a good practice to leverage the ordering of codecs as a way to migrate the database? Since based on this comment the order is guaranteed to be respected?

https://github.com/scodec/scodec/blob/d7d936b25dbb8f0ecb2a036ec14b068d4548e30d/shared/src/main/scala/scodec/codecs/package.scala#L1745-L1746

Specifically, in the following example class Foo has been upgraded, and we use the discriminated codec to decode from both old and new versions and always encode to the new version:

```scala
sealed trait Data

// this is the old version of Foo
//case class Foo(a: String) extends Data
case class Foo(a: String, b: Int) extends Data

case class Bar(b: Double) extends Data

// old codecs
// val fooCodec: Codec[Foo] = ...
//val codec = discriminated[Data].by(uint16)
//    .typecase(0x00, fooCodec)
//    .typecase(0x01, barCodec)

// note that foo1Codec decodes old versions of Foo and encode to the new version
val foo1Codec: Codec[Foo] = ...
val foo2Codec: Codec[Foo] = ...
val barCodec: Codec[Bar] = ...

val codec = discriminated[Data].by(uint16)
    .typecase(0x02, foo2Codec)
    .typecase(0x00, foo1Codec)
    .typecase(0x01, barCodec)
```

**Comment by mpilquist** [comment]
That looks fine to me. The linked comment about ordering is referring to that specific example, where a value to encode is matched against each `case` statement. In your case, `typecase` ordering works similarly -- the first entry that matches when encoding is the one that is used, so including `foo2Codec` before `foo1Codec` is correct.

**Comment by pm47** [comment]
Great, thanks!
