### ISSUE TITLE
pbcd codec pads right instead of left.

### ISSUE THREAD

**Issue by lJoublanc** [scodec/scodec#126]
According to a number of examples, including [wikipedia](https://en.wikipedia.org/wiki/Densely_packed_decimal#Examples) and [here](http://speleotrove.com/decimal/DPDecimal.html) (taking note that the encodings are the same for BCD for integers up to 79), the following is incorrect:
```
scala> pbcd(3).encode(79).require.toBin
res1: String = 011110010000
```
It should result in `0000 0111 1001`, i.e. the input `79` is implicitly `079` when the number of nibbles > the digits in the input. It appears that the codec is right-padding the zeros, whereas it should be left-padding them.

I'm not entirely certain what I'm saying is correct - if somebody can confirm this, I'm happy to implement a fix. @alvaroc1 ?

**Comment by alvaroc1** [comment]
@lJoublanc It could very well be the case, I had only one use case when I wrote it and i may have missed a bug like that. I'll check for sure tonight.
