### ISSUE TITLE
Maven artifactId changed in 1.10.4 release

### ISSUE THREAD

**Issue by ajaychandran** [scodec/scodec#134]
[scodec-core](https://search.maven.org/artifact/org.scodec/scodec-core_2.12/1.10.3/bundle) has been renamed to [core](https://search.maven.org/artifact/org.scodec/core_2.12/1.10.4/jar).

**Comment by mpilquist** [comment]
Argh! Thanks for spotting. I'll fix and release a 1.10.5.
