### ISSUE TITLE
intelliJ IDEA No implicit for prameter auto 

### ISSUE THREAD

**Issue by yuer2016** [scodec/scodec#137]
in intelliJ IDEA 2018.3 CoproductsExample.scala 
![image](https://user-images.githubusercontent.com/15603845/51468600-61903f80-1daa-11e9-8de3-00e86b619c2a.png) Prompt for an error,But it can run ,I checked the source code, find coproduct function need  implicit auto: codecs.CoproductBuilderAuto[A] parameter ,I don't understand when this parameter was built. How can I eliminate this error? Many thanks !

**Comment by aartigao** [comment]
@mpilquist I think this question can be closed too. IntelliJ is known to give false negatives when resolving implicits, but this is not an issue with scodec.
