### ISSUE TITLE
Make a release with new scodec-bits

### ISSUE THREAD

**Issue by sideeffffect** [scodec/scodec#245]
Hello @mpilquist , could you please make a release of `scodec-core` containing the newest `scodec-bits`?

**Comment by mpilquist** [comment]
I could though note everything is compatible with current releases, so releasing scodec-core would only to avoid evictions. BTW, I suspect we'll have a lot of scodec-bits releases coming up - one per Dotty release until Scala 3 final.

**Comment by sideeffffect** [comment]
I would like to have a new release of `scodec-bits`, because it will contain `ByteVector` that implements `Comparable`. I need that to be able to make an `Order` instance for `ByteVector` in `scodec-cats` this PR https://github.com/scodec/scodec-cats/pull/14

**Comment by mpilquist** [comment]
@sideeffffect Ah, use 1.1.19, which was released this weekend. Though looks like we're also going to have to release 1.1.20 to pick up https://github.com/scodec/scodec-bits/pull/221.

**Comment by sideeffffect** [comment]
Sorry, I actually meant to say I would nee a new release of `scodec-core`
