### ISSUE TITLE
BitVector.reverseBitOrder unreliable on non-whole-byte BitVectors

### ISSUE THREAD

**Issue by SattaiLanfear** [scodec/scodec#318]
When using `reverseBitOrder` on a `BitVector` that has a number of bits that is greater than one byte, and not a whole number of bytes, it drops data from the start of the `BitVector`.

Sample from a scratch file I was using to examine the problem:
```scala
import scodec.bits._

val v = bin"10101010 10101000 0000"
val bin = v.toBin
val binReadable = v.toBin.sliding(4, 4).mkString(" ")
val pop = v.populationCount
val reversed = v.reverseBitOrder
val reversedBin = reversed.toBin
val reversedBinReadable = reversed.toBin.sliding(4, 4).mkString(" ")
val reversedPop = reversed.populationCount
```

Yields:
```console
import scodec.bits._

val v: scodec.bits.BitVector = BitVector(20 bits, 0xaaa80)
val bin: String = 10101010101010000000
val binReadable: String = 1010 1010 1010 1000 0000
val pop: Long = 7
val reversed: scodec.bits.BitVector = BitVector(20 bits, 0x51500)
val reversedBin: String = 01010001010100000000
val reversedBinReadable: String = 0101 0001 0101 0000 0000
val reversedPop: Long = 5
```

It's clear from the fact that the population count on the original, and the reversed `BitVector`s that bits were lost.

Looking at the source it appears that after it reverses all of the data, it then just drops bits from the start of the `BitVector` which in a bit-vector larger than 8 bits, will be removing data that is entirely valid.

**Comment by mpilquist** [comment]
Thanks for the report -- fixed in https://github.com/scodec/scodec-bits/pull/294
