### ISSUE TITLE
Cross-Compiling scala 2.13 and scala 3 against scodec-core

### ISSUE THREAD

**Issue by cornerman** [scodec/scodec#365]
I want to cross-compile a library for scala 2.13 and scala 3. There I am depending on `scodec-core`.
Now the new version `2.1.0` is only released for scala 3 and not for scala 2.13.
Is it planned to release `2.1.0` for scala 2.13 as well or how could I depend on different versions for different scala version?

**Comment by cornerman** [comment]
For now, I am selecting different version for each scala versions, like this:

```
    libraryDependencies ++= (CrossVersion.partialVersion(scalaVersion.value) match {
      case Some((3, _)) => Seq(
        Deps.scodec.core2.value % Optional,
        Deps.scodec.bits.value  % Optional,
      )
      case _ => Seq(
        Deps.scodec.core.value % Optional,
        Deps.scodec.bits.value % Optional,
      )
    })
```

**Comment by mpilquist** [comment]
That’s the right approach. See fs2-protocols for an example: https://github.com/typelevel/fs2/tree/main/protocols/shared/src

**Comment by cornerman** [comment]
Thanks. Then I will close this issue. It was just a bit confusing for me to have two different versions.
