### ISSUE TITLE
Release 1.7.0 artifact?

### ISSUE THREAD

**Issue by prettynatty** [scodec/scodec#45]
It seems v1.7.0 is finished but there is not artifact in sonatype releases.

**Comment by mpilquist** [comment]
It's on Maven Central here: http://search.maven.org/#artifactdetails%7Corg.scodec%7Cscodec-core_2.11%7C1.7.0%7Cbundle

Note the groupId change from `org.typelevel` to `org.scodec`. That's probably why you aren't seeing it.

**Comment by prettynatty** [comment]
Thanks.
