### ISSUE TITLE
Scalastyle?

### ISSUE THREAD

**Issue by vkostyukov** [scodec/scodec#48]
@mpilquist would you be interested in a PR that enables Scalastyle plugin in scodec?

**Comment by mpilquist** [comment]
I don't think so, though I'm happy to hear arguments for it. I've tried scalastyle a few times and the results haven't compelled me to add it. I've been considering adding scalariform though.

**Comment by vkostyukov** [comment]
I use it quite heavily in [Finch](https://github.com/finagle/finch). In coupe with WartRemover it enables a reasonable amount of checks. For example, before Scalastyle we've missed the PR that accidentally uses Windows line breaks in the code instead of Unix/Linux ones. 

Although, I was also thinking enabling Scalariform in Finch. So, I can experiment with it there and then make a similar PR against scodec.
