### ISSUE TITLE
decodeValue has disappeared with no suggested replacement

### ISSUE THREAD

**Issue by jedesah** [scodec/scodec#51]
`codec.decodeValue` has disappeared and there is no suggested replacement in the changelog.

**Comment by jedesah** [comment]
`codec.decode(bits).map(_.value)` works I guess, but it's a bit long. Maybe it could at least be mentioned in the release notes even though it is fairly easy to derive from the others.

**Comment by mpilquist** [comment]
I'm happy to add this method back if you'd like it. I think this was cut when `encodeValid` and `decodeValidValue` methods were removed.

**Comment by jedesah** [comment]
Thank you for offering. If no one has any objections, I for one, would like
it if it were re-introduced.

**Comment by mpilquist** [comment]
Will be in scodec-core 1.7.2
