### ISSUE TITLE
Codec.upcast throws "java.lang.InternalError: Malformed class name" for nested classes

### ISSUE THREAD

**Issue by ajaychandran** [scodec/scodec#55]
The underlying issue is the call to `getSimpleName`.
See https://issues.scala-lang.org/browse/SI-2034

 java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1195)
	at scodec.Codec$$anon$4.encode(Codec.scala:341)

```scala
  final def upcast[B >: A](implicit m: Manifest[A]): Codec[B] = new Codec[B] {
    def sizeBound: SizeBound = self.sizeBound
    def encode(b: B) = b match {
      case a: A => self encode a
      case _ => Attempt.failure(Err(s"${b.getClass.getSimpleName} is not a ${m.runtimeClass.getSimpleName}"))
    }
    def decode(bv: BitVector) = self decode bv
    override def toString = self.toString
  }
```

**Comment by mpilquist** [comment]
Thanks for reporting this. Fixed in e981c60c5e14ab2ff123c1b21407ad058445d3e4 by removing use of Java reflection in favor of Shapeless's `Typeable`.
