### ISSUE TITLE
ScalaJs Compatibility 

### ISSUE THREAD

**Issue by omidb** [scodec/scodec#60]
Hi,

I wanted to know if Scodec is compatible with ScalaJS?

Thanks,

**Comment by mpilquist** [comment]
Hi,

Scala.js compatibility is coming in the 1.8 release -- hopefully within the next week.

Cheers

**Comment by omidb** [comment]
Awesome!

**Comment by mpilquist** [comment]
Released 1.8.0 yesterday with Scala.js support.
