### ISSUE TITLE
discriminated lazy codec failing roundtrip

### ISSUE THREAD

**Issue by alissapajer** [scodec/scodec#63]
Hi, here's a test that's not passing that I believe should be:

```scala
    "support discriminated recursive codec" in {
      sealed trait Message
      case class Batch(msgs: List[Message]) extends Message
      case class Single(msg: String) extends Message

      lazy val codec: Codec[Message] = lazily {
        discriminated[Message].by(uint8).
          typecase(0, utf8.as[Single]).
          typecase(1, list(codec).as[Batch])
      }

      val msg: Message = Batch(List(Single("first"), Single("second"), Single("third")))

      roundtrip(codec, msg)
    }
```

The output when run is:
```
[info] - should support discriminated recursive codec *** FAILED *** (122 milliseconds)
[info]   Batch(List(Single(firstsecondthird))) did not equal Batch(List(Single(first), Single(second), Single(third))) (CodecSuite.scala:26)
```
The strings inside each `Single` are concatted when they shouldn't be, and so the roundtrip fails.

I've pushed this failing test to my fork on branch `bug/lazy`. I can PR the branch with the broken test, if that would be useful. I put the test in `HListCodecTest.scala`.

**Comment by alissapajer** [comment]
Update: this appears to be an issue with `String` but not with `Int`. When `Single` is instead:
```scala
case class Single(msg: Int) extends Message
```
the test successfully roundtrips. I just pushed a second (passing) test with `Int` to the same branch.

**Comment by mpilquist** [comment]
Hi!

Yeah, the `string`, `utf8`, and `ascii` codecs do not round trip -- they are greedy and process the entire buffer when decoding. See the notes on greedy here: http://scodec.org/guide/Simple+Value+Codecs.html#Strings

The same example with `utf8_32` should round trip though.

**Comment by alissapajer** [comment]
Ah ok, interesting, thanks!
