### ISSUE TITLE
Standard Codecs for Literals encoded as Char

### ISSUE THREAD

**Issue by sirinath** [scodec/scodec#66]
Some protocols use plain char to represent numbers and other types. So is it possible to have some standards codecs for such decoding.

E.g.

 - +1_000.3
 - -1,000
 - 1k
 - 0b101010101011
 - -0xHA
 - 0o123
 - etc.

**Comment by mpilquist** [comment]
In order to generically support characters, we'd need a `Codec[Char]` that's dependent on a `Charset`. That is problematic though, as Java's charset support does not support decoding a single character.

**Comment by sirinath** [comment]
There will be many character encodings hence it is best the treat the characters as bytes or bits and work out the result only. E.g. ascii"-1.3e10" to -1.3e10. Similarly other encodings.

**Comment by mpilquist** [comment]
I don't follow -- the existing string codecs can handle decoding sequences of characters. I don't see a way to implement a generic `def char(implicit cs: Charset): Codec[Char]` using the JDK charset support, given that `CharsetDecoder` does not support decoding a single character and the fact that many charsets use a variable number of bytes per character.

**Comment by sirinath** [comment]
Only other things is for hex, octal, binary different prefixing, suffixing schemes may be used, or may not use any in which case the user must supply the interpretation.

If someone has written a JSON library using Scodec you might be able to borrow all the type conversion features with some modification to suite cases not present in JSON.

**Comment by mpilquist** [comment]
Sorry, I'm not sure what you mean. Could you maybe post some stubbed out example combinators or skeleton unit tests that show expected behavior? Based on the original issue, I thought you were looking for a `def char(implicit cs: Charset): Codec[Char]`, but I'm not sure about that now after re-reading.

**Comment by sirinath** [comment]
```
val a:  Codec[String] = ascii"100"
val i = CodedStringToUInt(a)
```

**Comment by mpilquist** [comment]
What would the following expressions evaluate to?

 - `a.encode("100")`
 - `a.encode("0")`
 - `a.encode("foo")`

**Comment by sirinath** [comment]
- a.encode("100") -> Codec[String] | Decoded into any number type, can be interpreted as decimal, binary, octal or hex based on the decoder used
 - a.encode("0") -> Codec[String] | Decoded into any number type, can be interpreted as decimal, binary, octal or hex based on the decoder used
 - a.encode("foo") -> Codec[String] | Decoding error if a numeric type is used.

**Comment by mpilquist** [comment]
In your example, the val a is a Codec[String], which means each of the above must evaluate to an Attempt[BitVector]. Could you provide the expected result for each expression?

The existing literal codecs all have type Codec[Unit], for they need no value in order to encode -- they use the literal value converted to binary.

**Comment by sirinath** [comment]
I am looking to read values over the wire in text based protocols like FIX. So any encode should be some character encoded type and any decode would be any value represented by the string.

If it is ascii when you encode you get the binary representation of the ascii text. In decoding if the text represents another type, say Int, you should be able to parse the text into the relevant type.

**Comment by sirinath** [comment]
Above is BitVector not Codec[String]

**Comment by mpilquist** [comment]
OK, I think I understand what you are looking for now. Try this:

```scala
def attemptParseInt(s: String): Attempt[Int] = 
  try Attempt.successful(s.toInt) catch { case e: NumberFormatException => Attempt.failure(Err(e.getMessage)) }
val x: Codec[Int] = ascii.narrow[Int](attemptParseInt, _.toString)
```

Be sure to read the info in the guide about how string codecs are greedy. http://scodec.org/guide/Simple+Value+Codecs.html#Strings

**Comment by sirinath** [comment]
Yes.

Can we have a standard codec which does this?

s.to* may not cover all cases.

**Comment by sirinath** [comment]
Also you have to deal with the case where you do not know how many characters that might turn up hence size is not known.

**Comment by mpilquist** [comment]
The example above handles that case -- the ascii codec decodes the entire input as an ascii string and then that string is converted to an int.

This type of codec is too protocol specific for the core library -- rather, the compositionality of the core library enables these types of protocol specific transformations. In this case, there are too many axes of variation -- the charset, the string length encoding, and the string to int conversion. We prefer to have a few number of general and transformable codecs than a huge number of hyper specific codecs.

**Comment by sirinath** [comment]
If these are implemented in the core these can be the basis of text based protocols like XML based messaging, JSON, etc. If there are implementation (SOAP, WS, JSON) using Scodec maybe you can use same codecs to be added to core which deal with data types.

If the conversion to string is avoided then it might be more efficient in terms of speed and GC.

I am not saying to add protocol specific things to the core but add great support for text based protocols where different data is represented as text.

**Comment by mpilquist** [comment]
I'm happy with the current core support for such codecs -- namely, users should select a `Codec[String]` which handles the specifics of their string encoding (charset, framing/sizing) and then narrow using a custom transformation.

I don't want to add a catalog of type conversions (e.g., `Int => String / String => Attempt[Int]`) as there are other libraries that handle that much better -- for example, [Twitter Bijection](https://github.com/twitter/bijection). Such libraries are more complete than what I'd want to include in scodec. I've been tempted to add these abstractions a few times, including an "injection" type, but ultimately have decided that doing so would result in a loss of focus on the core of the library. Better to leave such abstractions to libraries that have a focus on arbitrary type conversions, and then integrate them via `exmap` / `xmap` / `narrow` / `widen`.

With respect to text based protocols, depending on the specifics, you may be better using a text parser like [atto](https://github.com/tpolecat/atto), [sparse](https://github.com/djspiewak/sparse), or [fastparse](https://github.com/lihaoyi/fastparse) -- either in conjunction with scodec or as a replacement.
