### ISSUE TITLE
Codec Generator

### ISSUE THREAD

**Issue by sirinath** [scodec/scodec#67]
In order to make things faster in the long run is it possible to consider implementing Scodec as a compile time codec generator (similar to a parser generator). Perhaps with the option to hook into the generation phase soe you can generate the codes in other languages also using the same code base.

**Comment by sirinath** [comment]
Hopefully this will close any performance gap with other systems if not improve over them.

**Comment by mpilquist** [comment]
Compile time codec generation already exists in the form of derived codecs for case classes, thanks to Shapeless. See https://github.com/scodec/scodec/blob/be38fccc8428212385221632ed60d54fc8a19691/shared/src/test/scala/scodec/examples/DerivedCodecExamples.scala for examples.

The derived codecs take advantage of the compositional nature of the library. Instead, a monolithic codec could be generated at compile time that's very optimized. However, I think that's orthogonal to the goals of scodec-core. I also think tools like Avro are a good fit for such use cases.

**Comment by sirinath** [comment]
Please just keep the options open for the time being. Speed is never orthogonal.

**Comment by mpilquist** [comment]
By orthogonal, I meant that defining a protocol description language and compiling it to optimized Scala is orthogonal to scodec-core. Such a library could certainly tightly integrate with scodec-core, but it would be distinct. Nor do I want scodec-core to be implemented via a plethora of macros -- rather, the compositional nature is applied throughout the library and the only macro usage is in binding case classes to codecs via shapeless. This is an explicit design goal of the library.

With that said, we take performance very seriously. Some combinators have been heavily optimized. If you have any specific benchmarks or hotspots in mind, let me know.

Let me know if you have any more specific suggestions around compile time generation. I'm going to close this in the meantime, as I don't see it in scope of the core library.

**Comment by sirinath** [comment]
Maybe you can have a look at Scala LMS, Delite, etc. to do the optimisation?

**Comment by mpilquist** [comment]
An scodec-lms library would be interesting, though I'd still want that to be distinct from core. If you want to pursue such a library and want to discuss any details, let me know.

**Comment by sirinath** [comment]
Let me see what can be done.
