### ISSUE TITLE
listDelimited or vectorDelimited does not handle "twice" the marker

### ISSUE THREAD

**Issue by ogirardot** [scodec/scodec#72]
Hi, 
If I take back the example : 
```
scala> codec.decode(ascii.encode("i am delimited").require).require.value // List("i", "am", "delimited")
res106: List[String] = List(i, am, delimited)

scala> codec.decode(ascii.encode("i am  delimited").require).require.value // List("i", "am", "delimited")
res107: List[String] = List(i, am)
```

I don't think this is supposed to be the expected behaviour, no ?

Regards, 

Olivier.

**Comment by mpilquist** [comment]
Hi Olivier,

This is due to the `ascii` codec being greedy -- it doesn't encode the size of the string in the binary, rather, it always decodes the entire vector as ASCII. Try the same example with `ascii32`, which writes the length of the string as a 32-bit big endian signed int prior to writing the encoded string. Take a look http://scodec.org/guide/Simple+Value+Codecs.html#Strings for more information on String codec greediness.

**Comment by ogirardot** [comment]
I'm actually using kind of the same trick with bytes, to separate multiple segments separated by 0x3a, and I have the same kind of problems. Any tricks for that case ?

**Comment by mpilquist** [comment]
Yep, wrap your value codec with `variableSizeBytes`. For example:

```scala
scala> val c = listDelimited(hex"3a".bits, variableSizeBytes(uint16, bytes))
c: scodec.Codec[List[scodec.bits.ByteVector]] = listDelimited(BitVector(8 bits, 0x3a), variableSizeBytes(16-bit unsigned integer, bytes))

scala> val encoded = c.encode(List(hex"0000", hex"0101")).require
encoded: scodec.bits.BitVector = BitVector(72 bits, 0x000200003a00020101)

scala> val decoded = c.decode(encoded)
decoded: scodec.Attempt[scodec.DecodeResult[List[scodec.bits.ByteVector]]] = Successful(DecodeResult(List(ByteVector(2 bytes, 0x0000), ByteVector(2 bytes, 0x0101)),BitVector(empty)))
```

**Comment by ogirardot** [comment]
To better illustrate I have this delimiter : 
```
 val codec = listDelimited(BitVector(58), bytes)
```
And I have some data where some parts of it are "null" and "0x3a0x3a" is in the data. I would expect an empty BitVector would be crafted.

**Comment by mpilquist** [comment]
Ah okay, so `0x3a` may not appear in each value, right?

**Comment by ogirardot** [comment]
Here's a sample payload : 
```
val payload = hex"22053a613a93213a3af50320004290290060293a503a09783a362e35353935373a932122".bits
```
with double-quote (0x22) at the beginning and the end, and 0x3a to separate parts of the data

**Comment by mpilquist** [comment]
OK, general idea is to create a combinator that wraps a `Codec[A]`. On encode, it just delegates directly to `encode` on the wrapped codec. On decode, it takes the input `BitVector` and calls `takeWhile(b => b != 0x3f && b != 0x22)', and decoding the result using the wrapped codec, returning the `dropWhile` equivalent as the remainder. I can put together an example later tonight if you don't beat me to it. :)

**Comment by ogirardot** [comment]
of course I don't, thanks for your time !
If you've got time too, I'd love your input on the post I sent on the typelevel mailing-list, 
long story short, I'm trying to parse Packed Decimal data.

`uint4 ~ uint4 ...` where each is a number to create a `Long`. As you can guess I have trouble making "dynamic" sized HLists of uint4...

Any input appreciated, thanks again !

**Comment by mpilquist** [comment]
I just pushed an example of a codec which handles the pattern above: https://github.com/scodec/scodec/blob/79b145e5dbffc57d15770bb326a5b22f4fc2d903/shared/src/test/scala/scodec/examples/CustomDelimitedExample.scala

Let me know if that does what you need.

I need to look at your mailing list post in more detail -- I've been quite busy over the last few weeks so I haven't had a chance yet to take a deep look.

**Comment by ogirardot** [comment]
any chance to have a look ?
