### ISSUE TITLE
variableSizeBytes implicitly requires byte quantization

### ISSUE THREAD

**Issue by djspiewak** [scodec/scodec#80]
When I write it like that, it seems obvious, but it's far less obvious when you're *using* it.  Behold:

```scala
    "roundtrip a rle vector containing bool" in {
      val codec: Codec[Vector[Boolean]] = variableSizeBytes(int32, vector(bool))

      roundtripAll(codec, Seq(Vector(), Vector(true), Vector(false, false, true, false)))
    }
```

This doesn't work.  We found this (or rather, @alissapajer found it) when using `optional(bool, int32)`, which is a bit more obfuscated, but ultimately the problem is `bool`.  It's a codec which codes into single bits, meaning that the *bit* length of the coded vector is not necessarily mod 8, meaning that it doesn't round trip back through the byte quantizing.  The following *does* work:

```scala
    "roundtrip a rle vector containing bool" in {
      val codec: Codec[Vector[Boolean]] = variableSizeBits(int32, vector(bool))

      roundtripAll(codec, Seq(Vector(), Vector(true), Vector(false, false, true, false)))
    }
```

The culprit is here, inside of `variableSizeBytesLong`:

```scala
    private val codec = variableSizeBitsLong(size.xmap[Long](_ * 8, _ / 8), value, sizePadding * 8)
```

Obviously the integer division by 8 is lossy, and that's precisely what is showing up in the round trip failure.

@alissapajer and I talked about this quite a bit, and while yes, it is *right* in the name that you're dealing with bytes and not bits, it's still very surprising and in a real sense, composition-breaking.  I'm not sure exactly what to do, but it tripped us up for a while.

**Comment by mpilquist** [comment]
What do you think about failing encoding if the data doesn't evenly divide by 8? That is:

```scala
    private val codec = variableSizeBitsLong(size.widen[Long](_ * 8, bits => if (bits % 8 == 0) Attempt.successful(bits / 8) else Attempt.failure(Err("..."))), value, sizePadding * 8)
```

**Comment by djspiewak** [comment]
@mpilquist I think failing the encoding would be less confusing, since then at least it would be consistent.

**Comment by alissapajer** [comment]
@mpilquist I think failing encoding would be a fine solution. Then it's clear up front what's wrong.

**Comment by mpilquist** [comment]
OK great -- fixed in 1.8.3-SNAPSHOT and 1.9.0-SNAPSHOT. I'm planning on doing a 1.8.3 release some time in the next week.

By the way, one way to work around this issue is to use the `byteAligned` combinator. E.g., `variableSizeBytes(uint8, byteAligned(bool))` -- which will right pad the encoded vector up to the next byte boundary.

**Comment by alissapajer** [comment]
@mpilquist awesome, will be upgrading right away! :)

**Comment by mpilquist** [comment]
@alissapajer 1.8.3 is on Sonatype :)
