### ISSUE TITLE
publish for 2.12.0-RC2?

### ISSUE THREAD

**Issue by SethTisue** [scodec/scodec#89]
scodec-bits for 2.12.0-RC1 is on Maven Central, but scodec-core wasn't. did you hit any difficulties with RC1?

**Comment by mpilquist** [comment]
Only issue is no shapeless build for RC1.

**Comment by SethTisue** [comment]
Shapeless will be published for RC2 soon, I assume

**Comment by milessabin** [comment]
Very soon ...

**Comment by milessabin** [comment]
Done.

**Comment by SethTisue** [comment]
aaaaand it's on Maven Central now, too

**Comment by mpilquist** [comment]
Rec league basketball day after work. Building it now. ;)

**Comment by mpilquist** [comment]
1.10.3 is on Sonatype and on it's way to Central.
