### ISSUE TITLE
MpegPacketExample mishandles adaptationField

### ISSUE THREAD

**Issue by kylog** [scodec/scodec#93]
There are a couple related problems wrt mpeg transport stream packets which contain an adaptation field:

1. The [adaptationField](https://github.com/scodec/scodec/blob/d889f8b0f2679e17fb2ff8f1f1a69940e31fbc84/shared/src/test/scala/scodec/examples/MpegPacketExample.scala#L70-L75) doesn't include the adaptation field length byte (which is the first byte in the adaptation field). This means that the adaptationFieldFlags bits are all read from the wrong byte location, so are not valid.

1. If the packet contains both an adaptation field and payload, and since the sample code doesn't extract the field length, it doesn't make any attempt to shorten the payload by that size, instead specifying [a fixed 184](https://github.com/scodec/scodec/blob/d889f8b0f2679e17fb2ff8f1f1a69940e31fbc84/shared/src/test/scala/scodec/examples/MpegPacketExample.scala#L80) (which is valid when there's no adaptation field). It should instead subtract the adaptation field length from 184. Since there aren't 184 bytes left in such a packet it ends up throwing like so: `java.lang.IllegalArgumentException: payload: cannot acquire 1472 bits from a vector that contains 1464 bits`

1. The `adaptationField` also doesn't account for:

- transport private data
- adaptation extension
- stuffing bytes

**Comment by kylog** [comment]
Btw, I will try to work up a PR for some of the above. However, I'm new to both scodec and scala so it may take a little work :)

**Comment by mpilquist** [comment]
That would be great! The MPEG example definitely takes a bunch of shortcuts in order to keep the example small. A PR would certainly be welcome. Note that a more realistic set of types for working with MPEG transport streams exists in the scodec-protocols project: https://github.com/scodec/scodec-protocols/tree/series/1.0.x/src/main/scala/scodec/protocols/mpeg/transport

**Comment by kylog** [comment]
Ohhh ... I didn't know about that set of types. Thanks!

**Comment by mpilquist** [comment]
I added a disclaimer and a link to the production quality codec: https://github.com/scodec/scodec/commit/ef8863044cea5ac994d98f8866d8ea0a6874985d

Closing this issue for now but happy to merge a PR that makes the MPEG example more realistic without sacrificing its clarity as an example. The version in scodec-protocols should handle everything but there are lots of types to grapple with, which distracts some from learning the scodec combinators.
