### ISSUE TITLE
README.md seems to be outdated

### ISSUE THREAD

**Issue by unoexperto** [scodec/scodec#94]
I'm using Kryo at the moment. I've heard about scodec and decided to try it.

Sadly none of the examples from README.md work for me.

Since it doesn't say what dependencies to use I took the latest from Maven

```
          "org.scodec" %% "scodec-core" % "1.10.3",
          "org.scodec" %% "scodec-bits" % "1.1.2",
          "org.scodec" %% "scodec-scalaz" % "1.4.1",
```

Following code can't find codec for `String`

```
    val test = "sdfsfd"
    import scodec._
    import scodec.bits._
    import codecs._
    val encoded = Codec.encode(test)
```

error is 

```
Error:(296, 31) could not find Lazy implicit value of type scodec.Codec[String]
    val encoded = Codec.encode(test)
```

I was able to compile it by changing it to

```
val encoded = Codec.encode(test)(codecs.string(Charset.defaultCharset()))
```

but I doubt it's designed way of using it.

Then following code

```
    val firstCodec = (uint8 ~ uint8 ~ uint16)
    val result: DecodeResult[(Int ~ Int ~ Int)] = Codec.decode(firstCodec, BitVector(0x10, 0x2a, 0x03, 0xff))
    val add3 = (_: Int) + (_: Int) + (_: Int)
    val sum: DecodeResult[Int] = result map add3
```

doesn't compile because there is no `decode` with such prototype. I guess I can change it to 

```
val result: Attempt[DecodeResult[((Int, Int), Int)]] = Codec.decode(BitVector(0x10, 0x2a, 0x03, 0xff))(firstCodec)
```

but returning type is different so `result map add3` doesn't compile because there is no `map` method.

Could you please update readme to latest version of the library ?

Thank you.

**Comment by unoexperto** [comment]
Apparently `import scodec.codecs.implicits._` is what I needed.

**Comment by Tillaert** [comment]
I've had to modify the example, because Codec.decode now returns an ```Attempt[DecodeResult[(Int ~ Int ~ Int)]]```

The whole example now looks like this:

```scala
import scodec._
import scodec.bits._
import codecs._

// Create a codec for an 8-bit unsigned int followed by an 8-bit unsigned int followed by a 16-bit unsigned int
val firstCodec = uint8 ~ uint8 ~ uint16

// Decode a bit vector using that codec
val result: Attempt[DecodeResult[(Int ~ Int ~ Int)]] = Codec.decode(BitVector(0x10, 0x2a, 0x03, 0xff))(firstCodec)
// Successful(DecodeResult(((16,42),1023),BitVector(empty)))

// Sum the result
val add3 = (_: Int) + (_: Int) + (_: Int)

val sum: DecodeResult[Int] = result.require.map(add3)
// DecodeResult(1081,BitVector(empty))
```

**Comment by mpilquist** [comment]
Thanks for pointing this out. README has been updated.
