### ISSUE TITLE
Missing scodec.Codec[Command] implicit because of class with non-value fields

### ISSUE THREAD

**Issue by unoexperto** [scodec/scodec#95]
I'm sorry for posting it here but this issue is blocking me.

SO question http://stackoverflow.com/questions/41997534/missing-scodec-codeccommand-implicit-because-of-class-with-non-value-fields

I'm trying to use discriminators in existing project and something is wrong with my classes I guess.

Consider this [scodec example][1]. If I change `TurnLeft` and its codec to

    sealed class TurnLeft(degrees: Int) extends Command {
      def getDegrees: Int = degrees
    }
    implicit val leftCodec: Codec[TurnLeft] = uint8or16.xmap[TurnLeft](v => new TurnLeft(v), _.getDegrees)

I get

    Error:(x, x) could not find Lazy implicit value of type scodec.Codec[Command]
        val codec: Codec[Either[UnrecognizedCommand, Command]] = discriminatorFallback(unrecognizedCodec, Codec[Command])

It all works if I make `degrees` field value field. I suspect it's something tricky with shapeless. What should I do to make it work ?

Sample project that demonstrates the issue is [here][2].

  [1]: https://github.com/scodec/scodec/blob/series/1.10.x/shared/src/test/scala/scodec/examples/TlvExample.scala
  [2]: https://github.com/unoexperto/scodec_issue

**Comment by mpilquist** [comment]
Closing due to Miles answering on SO.
