### ISSUE TITLE
recover codec wont result in empty vector, when supplied with false

### ISSUE THREAD

**Issue by pchlupacek** [scodec/scodec#97]
optional(recover(constant(BitVector(Array('X')))), ascii))

when supplied with None will still encode to X. Cause seems to be in recover codec that always encodes to unit.

**Comment by mpilquist** [comment]
From `optional` scaladoc:
> When encoding, a `Some` results in `guard` encoding a `true` and `target` encoding the value. A `None` results in `guard` encoding a false and the `target` not encoding anything.

The guard here is `recover(constant(BitVector('X')))` -- recover codes ignore the true/false parameter on encode and always encodes the target.

This is indeed at odds with this claim from the scaladoc for `recover`:
> When encoding, a true results in the target codec encoding a unit whereas a false results in encoding of an empty vector.
 
So either scaladoc is wrong or the implementation is wrong. I lean towards fixing the implementation, though folks may be relying on the current broken behavior.

I'd like to hear @djspiewak's thoughts before deciding.

**Comment by ShaneDelmore** [comment]
I too found this behavior surprising.  Can you recommend a good workaround?

**Comment by maximeburri** [comment]
I believe that the implementation is wrong and the scaladoc behaviour is better. The current implementation is not `roundtrip`-able with the `optional` combinator and the `None` value (but only with the `Some` value). Example : 

```scala
    case class First(value: Int)
    case class Second(value: Int)
    case class Values(a: Option[First], b: Second)

    implicit val firstCodec = int8.as[First]
    implicit val secondCodec = int8.as[Second]
    implicit val valuesCodec = (
      optional(recover(constant(hex"01")), Codec[First]) ::
        constant(hex"02") :: Codec[Second]).as[Values]

    // encoding is 0x01010202 => roundtrip ok
    roundtrip(valuesCodec, Values(Some(First(1)),Second(2))) 

    // encoding is 0x*01*0202 => roundtrip fail
    roundtrip(valuesCodec, Values(None, Second(2))) 
```

But with the following fixed recover (`encode` check the boolean), the encoding with the `None` value is well `0x0202` and the `roundtrip` function works.

```scala
    class FixRecoverCodec(target: Codec[Unit], lookahead: Boolean) extends Codec[Boolean] {
      def sizeBound = target.sizeBound
      def encode(a: Boolean) = if(a) target.encode(()) else Attempt.successful(BitVector.empty)
      def decode(buffer: BitVector) =
        target.decode(buffer) match {
          case Attempt.Successful(DecodeResult(_, rest)) => Attempt.successful(DecodeResult(true, if (lookahead) buffer else rest))
          case f: Attempt.Failure => Attempt.successful(DecodeResult(false, buffer))
        }
      override def toString = if (lookahead) s"lookahead($target)" else s"recover($target)"
    }
    def recover(target: Codec[Unit]) = new FixRecoverCodec(target, false)
```

**Comment by djspiewak** [comment]
@mpilquist For some reason, I literally wasn't aware of this ticket until just now!

I cannot for the life of me remember why I had `recover` implemented with these semantics. I'm going to guess I was just wrong. :-)

**Comment by mpilquist** [comment]
@djspiewak Cool, thanks
@maximeburri Thanks for taking this on
